### ISSUE TITLE
Cannot call my own block in gnuradio     import cgl ImportError: No module named cgl

### ISSUE THREAD

**Issue by cgl-nudt** [EttusResearch/gr-ettus#52]
I can see my own block in gnuradio, but i can't run it. the file "cgl_testmux.xml" and "testmux.xml" I hava changed. I add my block in rfnoc_ddc.grc. but it can't run.
![image](https://user-images.githubusercontent.com/26371686/105124390-074f2400-5b15-11eb-840a-b845a5696f06.png)

rfnoc_ddc.py", line 29, in <module>
    import cgl
ImportError: No module named cgl

**Comment by mbr0wn** [comment]
I apologize for not having a better response, but that seems to be an issue on the side of the `gr-cgl` module you wrote. In your prefix, does `python3 -c 'import cgl'` work?

Also, since this is based on `maint-3.7`, I will close this now. If this issue persists, and you are convinced it's gr-ettus related, please reopen.
