### ISSUE TITLE
stream args: can't assign a specific SFP port using stream args in the rx streamer block

### ISSUE THREAD

**Issue by muaddib1984** [EttusResearch/gr-ettus#56]
i'm building a system with an X310 as the frontend receiver. i'd like to be able to use RFNoC blocks to split the stream from RX2 (RFA) into a high-rate(200Msps) stream and a decimated low-rate(5Msps) stream, sending high rate over SFP+ Port 0 and low-rate over SFP Port 1. Is that possible using stream args (channel=0,1 maybe?) in the rx streamer block? I can't seem to get any valid stream args to take.
I'm working on building the splitstream block into my image, so for now I have been able to get RFA-RX2 and RFB-RX2 streams into gnuradio using 2 rx streamers (flowgraph attached), but according to tcpdump/iftop the streams are muxed onto one interface?

can you help?
![rfnoc_graph](https://user-images.githubusercontent.com/70996692/118522466-1718f680-b70a-11eb-8666-faf721eaca93.png)

i have also posted a question on the usrp-users message board, but not gotten a response yet.
https://lists.ettus.com/empathy/thread/MKEWJTRONAY7RXUMXBMYM2W2ZV3EGEIQ

**Comment by mbr0wn** [comment]
This is a totally legitimate request. I've created #68 to address this, and the same change will also go into gr-uhd.

This requires understanding of adapter IDs, which are a not-so-well known part of the UHD API. As an example, if you create a session to an X310 with `addr=...,second_addr=...`, then you will have 2 adapters available. Adapter IDs are simply numbers, and start at 1 (because 0 is reserved for 'any adapter', or 'auto').

**Comment by mbr0wn** [comment]
There's two PRs in the pipe, for gr-ettus and UHD. This issue may get closed before they're all in, but they're all tracked.

**Comment by mbr0wn** [comment]
Fixed here via 75f3adbd0e6220d62480e87ab4e678e59eb91e74, in gr-uhd via https://github.com/gnuradio/gnuradio/pull/6347
