### ISSUE TITLE
rfnocmodtool can't import ettus

### ISSUE THREAD

**Issue by srrobo92** [EttusResearch/gr-ettus#57]
$ rfnocmodtool help
Traceback (most recent call last):
  File "/usr/local/bin/rfnocmodtool", line 7, in <module>
    from ettus.rfnoc_modtool import *
ModuleNotFoundError: No module named 'ettus'

Installed gnuradio 3.8 through ppa
Intalled master branch of uhd

**Comment by mbr0wn** [comment]
Not clear how you installed gr-ettus. Closing due to lack of information.

**Comment by marcivanmanalac** [comment]
I got this same error following the rfnoc workshop 4 part 2 install from source [guide](https://www.gnuradio.org/grcon/grcon20/grcon20_RFNoC_4_Part2.pdf) using ubuntu 20.04, uhd 4.0.0, and gr-ettus maint-3.8-uhd-4.0.

I see that the ettus module is in my /usr/local/lib/python3/dist-packages/ directory.

Were you able to remediate this problem? I was wondering if there was a way to just add it in the path or something rather than going all the way back and doing it over another way.

**Comment by marcivanmanalac** [comment]
I was able to just add the module to the python path as shown in the workshop [video](https://www.youtube.com/watch?v=M9ntwQie9vs&t=5480s) at 38:00.
