### ISSUE TITLE
USRP-X310 DDR3 1GB memory

### ISSUE THREAD

**Issue by 2444616578** [EttusResearch/gr-ettus#64]
I want to know  how can I use the 1GB DDR3 memory in USRP-X310.

Should I  search for the corresponding FPGA module in the fpga/x310 folder of UHD or gr_ettus folder? 
 
I am using UHD3.15 and GNURadio3.7

**Comment by michaelld** [comment]
@2444616578 This question is a more general question & not an issue with gr-ettus per se, which should be posted to the [USRP users group](https://lists.ettus.com/list/usrp-users.lists.ettus.com), not here. If you disagree then please reopen and explain the connection in detail so that someone can try to provide assistance.

Also: Those versions of UHD and GNU Radio are very old & will only work with somewhat older versions of gr-ettus. Please consider updating to UHD 4.2 and GNU Radio 3.8, since those are the versions compatible with gr-ettus MASTER branch HEAD. Latest releases of each is best.
